Repository electronic-structure/SIRIUS, pull requests merged in 2022-12, with the labels that each got.

#791 [docs] Fix link to spglib in README
  README.md
Labels: doc

#778 [feature] Implementation of the interface to geomtry optimization.
  CMakeLists.txt
  apps/dft_loop/CMakeLists.txt
  apps/dft_loop/sirius.scf.cpp
  apps/nlcg/sirius.nlcg.cpp
  apps/nlcg/sirius.test.nlcg.cpp
  apps/tests/test_fortran_api.f90
  src/CMakeLists.txt
  src/README.md
  src/api/sirius.f90
  src/api/sirius_api.cpp
  src/context/README.md
  src/context/config.hpp
  src/context/input_schema.json
  src/context/simulation_context.cpp
  src/context/simulation_context.hpp
  src/context/simulation_parameters.hpp
  src/density/density.cpp
  src/dft/dft_ground_state.cpp
  src/dft/dft_ground_state.hpp
  src/dft/energy.hpp
  src/dft/lattice_relaxation.hpp
  src/geometry/force.cpp
  src/geometry/force.hpp
  src/geometry/stress.cpp
  src/geometry/stress.hpp
  src/sirius.hpp
  src/unit_cell/unit_cell.cpp
  src/unit_cell/unit_cell.hpp
  src/utils/env.hpp
  src/utils/utils.hpp
  src/vcsqnm/README.md
  src/vcsqnm/historylist.hpp
  src/vcsqnm/periodic_optimizer.hpp
  src/vcsqnm/sqnm.hpp
  verification/test15/sirius.json
Labels: feature

#775 [fix] Adjust to the latest ELPA API
  src/linalg/eigenproblem.hpp
Labels: fix
