Repository electronic-structure/SIRIUS, pull requests merged in 2022-11, with the labels that each got.

#779 [fix] performance in ortgonalize()
  apps/tests/test_wf_ortho.cpp
  src/SDDK/wave_functions.hpp
  src/utils/utils.hpp
Labels: enhancement

#777 WIP: update api for python module, drop python2
  .github/workflows/build.yml
  CMakeLists.txt
  ci/dockerfiles/Dockerfile
  examples/python/Si.json
  examples/python/Si_dft.py
  python_module/CMakeLists.txt
  python_module/make_sirius_comm.hpp
  python_module/py_sirius.cpp
  spack/packages/sirius/package.py
  src/SDDK/wave_functions.hpp
Labels: enhancement

#782 [fix] printing the forces
  src/geometry/force.cpp
  verification/test17/output_ref.json
  verification/test17/sirius.json
Labels: bug

#784 [fix] Allocate wave-function from memory pool
  src/SDDK/wave_functions.hpp
  src/band/davidson.hpp
  src/context/simulation_context.cpp
Labels: enhancement

#787 [fix] PROFILE_START was used incorreclty
  src/density/occupation_matrix.cpp
Labels: bug

#732 [enhancement] Use C++ streams for output
  apps/atoms/atom.cpp
  apps/dft_loop/sirius.scf.cpp
  apps/nlcg/sirius.nlcg.cpp
  apps/nlcg/sirius.test.nlcg.cpp
  apps/tests/test_allgather.cpp
  apps/tests/test_comm_split.cpp
  apps/tests/test_eigen.cpp
  apps/tests/test_mem_alloc.cpp
  apps/tests/test_mpi_grid.cpp
  apps/tests/test_pstdout.cpp
  src/README.md
  src/SDDK/gvec.hpp
  src/api/sirius_api.cpp
  src/band/band.hpp
  src/band/davidson.hpp
  src/band/diag_full_potential.cpp
  src/band/diag_pseudo_potential.cpp
  src/band/solve.cpp
  src/beta_projectors/beta_projectors.hpp
  src/context/simulation_context.cpp
  src/context/simulation_context.hpp
  src/context/simulation_parameters.hpp
  src/density/augmentation_operator.cpp
  src/density/density.cpp
  src/dft/dft_ground_state.cpp
  src/dft/dft_ground_state.hpp
  src/geometry/force.cpp
  src/geometry/stress.cpp
  src/gpu/acc.hpp
  src/hamiltonian/hamiltonian_k.cpp
  src/hamiltonian/local_operator.cpp
  src/hamiltonian/non_local_operator.cpp
  src/hubbard/hubbard_matrix.cpp
  src/k_point/k_point.hpp
  src/k_point/k_point_set.cpp
  src/linalg/eigensolver.cpp
  src/mpi/communicator.cpp
  src/mpi/communicator.hpp
  src/potential/generate_d_operator_matrix.cpp
  src/potential/paw_potential.cpp
  src/potential/poisson.cpp
  src/potential/potential.hpp
  src/potential/xc.cpp
  src/radial/radial_integrals.hpp
  src/sht/sht.cpp
  src/symmetry/crystal_symmetry.cpp
  src/symmetry/crystal_symmetry.hpp
  src/unit_cell/atom.hpp
  src/unit_cell/atom_symmetry_class.cpp
  src/unit_cell/atom_type.cpp
  src/unit_cell/unit_cell.cpp
  src/unit_cell/unit_cell.hpp
  src/utils/rte.hpp
  src/utils/utils.cpp
  src/utils/utils.hpp
Labels: enhancement

#789 [fix] Only call PROFILE() at the beginning
  src/density/occupation_matrix.cpp
Labels: fix
