Repository electronic-structure/SIRIUS, pull requests merged in 2023-05, with the labels that each got.

#780 [feature] cuSolver potrf() and potri() interfaces
  src/gpu/cusolver.hpp
  src/linalg/linalg.hpp
Labels: feature

#835 Enable MPI settings for parallel verification tests
  apps/dft_loop/CMakeLists.txt
Labels: feature, enhancement

#836 [fix] Umpire allocator for the multiple device case
  src/SDDK/memory.hpp
Labels: fix
