Repository electronic-structure/SIRIUS, pull requests merged in 2023-10, with the labels that each got.

#898 Fix ScaLAPACK p*syevd
  src/linalg/eigenproblem.hpp
Labels: bug

#901 Make verification tests fail if exception is thrown
  apps/dft_loop/sirius.scf.cpp
Labels: fix, enhancement

#905 [refactor] change folder name from dft_loop to mini_app
  CMakeLists.txt
  apps/mini_app/CMakeLists.txt
  apps/mini_app/plot.cpp
  apps/mini_app/plot.py
  apps/mini_app/sirius.scf.cpp
  src/sirius.hpp
  verification/run_tests.x
  verification/run_tests_gpu.x
  verification/run_tests_parallel.x
  verification/run_tests_parallel_gpu.x
  verification/run_tests_parallel_k.x
  verification/run_tests_parallel_k_gpu.x
Labels: refactor

#900 [feature] Support for DLA-Future
  CMakeLists.txt
  README.md
  cmake/siriusConfig.cmake.in
  spack/packages/sirius/package.py
  spack/repo.yaml
  src/CMakeLists.txt
  src/context/config.hpp
  src/context/input_schema.json
  src/context/simulation_context.cpp
  src/k_point/k_point.cpp
  src/linalg/blacs_grid.hpp
  src/linalg/dmatrix.hpp
  src/linalg/eigenproblem.cpp
  src/linalg/eigenproblem.hpp
  src/linalg/eigensolver.cpp
  src/linalg/eigensolver.hpp
  src/sirius.hpp
Labels: feature
