Repository electronic-structure/SIRIUS, pull requests merged in 2023-08, with the labels that each got.

#880 [fix] spin index for hphi
  src/hamiltonian/s_u_operator.cpp
Labels: bug

#882 [fix] add contribution from PAW density to inner product of mixing density residuals
  src/function3d/paw_field4d.hpp
  src/mixer/mixer_functions.cpp
Labels: fix

#884 [feature] restore function to set density matrix
  src/api/sirius.f90
  src/api/sirius_api.cpp
Labels: feature

#883 [enhancement] remove code repetition in construction of the real density matrix
  src/density/density.cpp
  src/density/density.hpp
  src/potential/paw_potential.cpp
  src/potential/potential.hpp
Labels: enhancement

#885 [enhancement] tweak and debug scf convergence
  src/api/sirius_api.cpp
  src/band/band.hpp
  src/band/davidson.hpp
  src/band/davidson_result_t.hpp
  src/band/residuals.hpp
  src/band/solve.cpp
  src/density/occupation_matrix.cpp
  src/dft/dft_ground_state.cpp
  src/function3d/periodic_function.hpp
  src/mpi/communicator.hpp
  src/potential/xc_mt.cpp
  src/utils/env.hpp
Labels: enhancement

#887 [enhancement] generate paw density in api call
  src/api/sirius.f90
  src/api/sirius_api.cpp
  src/band/check_wave_functions.hpp
  src/density/density.cpp
  src/density/density.hpp
  src/potential/potential.cpp
  src/potential/potential.hpp
  src/potential/xc_mt.cpp
Labels: enhancement

#889 [refactor] Get rid of band class in favour of pure functions
  apps/dft_loop/sirius.scf.cpp
  apps/tests/test_davidson.cpp
  python_module/py_sirius.cpp
  src/CMakeLists.txt
  src/api/sirius_api.cpp
  src/band/band.cpp
  src/band/davidson_result_t.hpp
  src/band/diag_pseudo_potential.cpp
  src/band/solve.cpp
  src/dft/dft_ground_state.cpp
  src/dft/dft_ground_state.hpp
  src/hamiltonian/check_wave_functions.hpp
  src/hamiltonian/davidson.hpp
  src/hamiltonian/diagonalize.hpp
  src/hamiltonian/diagonalize_fp.hpp
  src/hamiltonian/diagonalize_pp.hpp
  src/hamiltonian/generate_subspace_matrix.hpp
  src/hamiltonian/initialize_subspace.hpp
  src/hamiltonian/residuals.hpp
  src/multi_cg/multi_cg.hpp
  src/sirius.hpp
  src/unit_cell/atom_symmetry_class.cpp
  src/unit_cell/unit_cell.cpp
  verification/test01/sirius.json
  verification/test02/sirius.json
  verification/test03/sirius.json
Labels: refactor

#890 use const where possible
  apps/tests/test_davidson.cpp
  src/SDDK/memory.hpp
  src/dft/dft_ground_state.cpp
  src/hamiltonian/check_wave_functions.hpp
  src/hamiltonian/davidson.hpp
  src/hamiltonian/diagonalize.hpp
  src/hamiltonian/diagonalize_fp.hpp
  src/hamiltonian/diagonalize_pp.hpp
  src/hamiltonian/generate_subspace_matrix.hpp
  src/hamiltonian/hamiltonian.hpp
  src/hamiltonian/hamiltonian_k.cpp
  src/hamiltonian/initialize_subspace.hpp
  src/hamiltonian/non_local_operator.hpp
  src/hamiltonian/s_u_operator.cpp
  src/hubbard/hubbard_matrix.hpp
  src/k_point/k_point.hpp
  src/multi_cg/multi_cg.hpp
  src/unit_cell/atomic_data.hpp
Labels: refactor
