Repository electronic-structure/SIRIUS, pull requests merged in 2023-07, with the labels that each got.

#851 [enhancement] Simplify ELPA setup
  src/context/simulation_context.cpp
  src/k_point/k_point.cpp
  src/linalg/eigenproblem.cpp
  src/linalg/eigenproblem.hpp
  src/linalg/eigensolver.hpp
Labels: enhancement

#853 [enhancement] LAPW functions
  src/context/simulation_context.cpp
  src/context/simulation_context.hpp
  src/density/density.cpp
  src/density/density.hpp
  src/function3d/make_periodic_function.hpp
  src/geometry/force.cpp
  src/geometry/stress.cpp
  src/lapw/generate_gvec_ylm.hpp
  src/lapw/generate_sbessel_mt.hpp
  src/lapw/step_function.hpp
  src/lapw/sum_fg_fl_yg.hpp
  src/potential/poisson.cpp
  src/potential/potential.cpp
  src/potential/potential.hpp
Labels: enhancement

#855 [enhancement] re-introduce check_wave_functions() function
  src/SDDK/wave_functions.hpp
  src/band/band.cpp
  src/band/band.hpp
  src/band/check_wave_functions.hpp
  src/band/solve.cpp
  src/hamiltonian/hamiltonian.hpp
  src/k_point/k_point.hpp
  src/k_point/k_point_set.hpp
Labels: enhancement

#862 [feature] new split index implementation
  apps/tests/test_allgather.cpp
  apps/tests/test_wf_ortho.cpp
  apps/tests/test_wf_trans.cpp
  apps/unit_tests/test_splindex.cpp
  python_module/py_sirius.cpp
  src/SDDK/splindex.hpp
  src/SDDK/wave_functions.hpp
  src/api/sirius_api.cpp
  src/band/band.cpp
  src/band/band.hpp
  src/band/diag_full_potential.cpp
  src/band/residuals.hpp
  src/band/solve.cpp
  src/density/density.cpp
  src/density/density.hpp
  src/dft/dft_ground_state.cpp
  src/dft/energy.cpp
  src/fft/fft.hpp
  src/fft/gvec.cpp
  src/fft/gvec.hpp
  src/function3d/field4d.hpp
  src/function3d/paw_field4d.hpp
  src/function3d/periodic_function.hpp
  src/function3d/spheric_function_set.hpp
  src/geometry/force.cpp
  src/geometry/non_local_functor.hpp
  src/geometry/stress.cpp
  src/hamiltonian/hamiltonian.cpp
  src/hamiltonian/hamiltonian_k.cpp
  src/hamiltonian/non_local_operator.hpp
  src/hamiltonian/non_local_operator_base.hpp
  src/hubbard/hubbard_occupancies_derivatives.cpp
  src/k_point/generate_fv_states.cpp
  src/k_point/k_point.cpp
  src/k_point/k_point_set.cpp
  src/k_point/k_point_set.hpp
  src/linalg/dmatrix.cpp
  src/linalg/dmatrix.hpp
  src/mixer/mixer_functions.cpp
  src/nlcglib/adaptor.cpp
  src/nlcglib/inverse_overlap.hpp
  src/nlcglib/overlap.hpp
  src/nlcglib/ultrasoft_precond.hpp
  src/potential/paw_potential.cpp
  src/potential/poisson.cpp
  src/potential/potential.hpp
  src/potential/xc.cpp
  src/potential/xc_mt.cpp
  src/radial/radial_integrals.cpp
  src/radial/radial_integrals.hpp
  src/strong_type.hpp
  src/symmetry/symmetrize_forces.hpp
  src/symmetry/symmetrize_mt_function.hpp
  src/traits.hpp
  src/typedefs.hpp
  src/unit_cell/atom.hpp
  src/unit_cell/basis_functions_index.hpp
  src/unit_cell/unit_cell.cpp
  src/unit_cell/unit_cell.hpp
Labels: feature

#863 [enhancement ] switch to C++17
  CMakeLists.txt
Labels: enhancement

#864 [feature] implement SIRIUS_CONFIG environment variable
  src/context/simulation_context.hpp
  src/utils/env.hpp
Labels: feature

#869 [fix] capture exceptions in mini-app
  apps/dft_loop/sirius.scf.cpp
Labels: fix

#832 [cmake] Use SIRIUS namespace convention for options and other SIRIUS …
  .github/workflows/build.yml
  CMakeLists.txt
  README.md
  apps/dft_loop/CMakeLists.txt
  apps/tests/CMakeLists.txt
  apps/tests/test_davidson.cpp
  apps/tests/test_hloc.cpp
  apps/tests/test_wf_ortho.cpp
  apps/tests/test_wf_trans.cpp
  apps/unit_tests/test_fft_correctness_1.cpp
  apps/unit_tests/test_fft_correctness_2.cpp
  ci/baseimage.cuda.Dockerfile
  ci/baseimage.rocm.Dockerfile
  ci/github-ci/spack/packages/sirius/cmake-fix-shared-library-installation.patch
  ci/github-ci/spack/packages/sirius/link-libraries-fortran.patch
  ci/github-ci/spack/packages/sirius/mpi_datatypes.patch
  ci/github-ci/spack/packages/sirius/package.py
  ci/github-ci/spack/packages/sirius/strip-spglib-include-subfolder.patch
  ci/github-ci/spack/repo.yaml
  cmake/modules/FindCRAY_LIBSCI.cmake
  cmake/modules/FindElpa.cmake
  cmake/modules/FindFFTW.cmake
  cmake/modules/FindLibSPG.cmake
  cmake/modules/FindLibVDWXC.cmake
  cmake/modules/FindLibXC.cmake
  cmake/modules/FindMAGMA.cmake
  cmake/modules/FindMKL.cmake
  cmake/modules/FindPython2.cmake
  cmake/modules/FindPythonSupport.cmake
  cmake/modules/FindSCALAPACK.cmake
  cmake/siriusConfig.cmake.in
  doc/CMakeLists.txt
  spack/packages/sirius/package.py
  src/CMakeLists.txt
  src/band/band.cpp
  src/band/diag_pseudo_potential.cpp
  src/band/solve.cpp
  src/beta_projectors/beta_projectors_base.cpp
  src/context/simulation_context.cpp
  src/context/simulation_context.hpp
  src/density/density.cpp
  src/density/occupation_matrix.cpp
  src/dft/dft_ground_state.cpp
  src/fft/fft.hpp
  src/geometry/force.cpp
  src/geometry/stress.cpp
  src/hamiltonian/hamiltonian.cpp
  src/hamiltonian/hamiltonian_k.cpp
  src/hamiltonian/local_operator.cpp
  src/hamiltonian/non_local_operator.cpp
  src/hamiltonian/s_u_operator.cpp
  src/k_point/generate_fv_states.cpp
  src/k_point/generate_spinor_wave_functions.cpp
  src/k_point/k_point.cpp
  src/k_point/k_point_set.cpp
  src/k_point/k_point_set.hpp
  src/linalg/dmatrix.cpp
Labels: enhancement

#874 [refactor] simplify JSON schema
  src/band/band.hpp
  src/beta_projectors/beta_projectors.hpp
  src/context/config.hpp
  src/context/input_schema.json
  src/context/simulation_context.cpp
  src/context/simulation_parameters.hpp
  src/density/augmentation_operator.cpp
  src/density/density.cpp
  src/hamiltonian/hamiltonian_k.cpp
  src/hamiltonian/local_operator.cpp
  src/hamiltonian/non_local_operator.cpp
  src/hamiltonian/s_u_operator.cpp
  src/potential/poisson.cpp
  src/potential/potential.cpp
  src/potential/potential.hpp
  src/potential/xc.cpp
  src/radial/radial_integrals.hpp
  src/utils/env.hpp
  src/utils/utils.hpp
Labels: refactor

#783 [feature] use potrf from cuSolver
  apps/tests/CMakeLists.txt
  apps/tests/test_eigen.cpp
  apps/tests/test_potrf.cpp
  src/SDDK/wave_functions.hpp
  src/gpu/cusolver.hpp
  src/linalg/dmatrix.cpp
  src/linalg/linalg.hpp
  src/testing.hpp
Labels: enhancement
