Repository electronic-structure/SIRIUS, pull requests merged in 2024-01, with the labels that each got.

#945 [cmake] add missing REQUIRED
  CMakeLists.txt
Labels: fix

#941 [fix] radial solver
  apps/atoms/atom.cpp
  apps/tests/CMakeLists.txt
  apps/tests/test_enu.cpp
  apps/tests/test_radial_solver.cpp
  src/context/config.hpp
  src/context/input_schema.json
  src/hamiltonian/hamiltonian_k.cpp
  src/radial/radial_solver.hpp
  src/unit_cell/atom_symmetry_class.cpp
  src/unit_cell/atom_type_base.hpp
  src/unit_cell/unit_cell.cpp
  verification/test31/H.json
  verification/test31/output_ref.json
  verification/test31/sirius.json
Labels: fix

#951 [fix] use RTE_THROW() macro in more places
  src/core/la/linalg.hpp
  src/radial/radial_solver.hpp
Labels: enhancement

#953 [feature] control muffin-tin lapw radii from the main input file
  src/context/config.hpp
  src/context/input_schema.json
  src/context/simulation_parameters.cpp
  src/unit_cell/atom_type.cpp
Labels: feature

#956 [enhancement] more robust calculation of radial functions
  src/function3d/periodic_function.hpp
  src/hamiltonian/diagonalize_fp.hpp
  src/hamiltonian/hamiltonian.cpp
  src/hamiltonian/hamiltonian.hpp
  src/potential/potential.hpp
  src/unit_cell/atom_symmetry_class.cpp
  src/unit_cell/atom_symmetry_class.hpp
Labels: enhancement
